(ns extensions.workflow-loader.text
  (:require
   [psi.agent-session.workflow.text :as core]))

(def parse-mode core/parse-mode)
(def available-workflows-text core/available-workflows-text)
(def active-runs-text core/active-runs-text)
(def delegate-list-text core/delegate-list-text)
(def workflow-run-started-text core/workflow-run-started-text)
(def workflow-run-result-text core/workflow-run-result-text)
(def delegate-continued-text core/delegate-continued-text)
(def delegate-removed-text core/delegate-removed-text)
(def unknown-action-text core/unknown-action-text)
(def error-text core/error-text)
(def widget-placement core/widget-placement)
(def run-status-icon core/run-status-icon)
(def run-widget-lines core/run-widget-lines)
(def build-prompt-contribution core/build-prompt-contribution)
(def parse-delegate-command core/parse-delegate-command)
(def completion-notification-text core/completion-notification-text)
(def completion-entry-heading core/completion-entry-heading)
(def completion-entry-content core/completion-entry-content)
