(ns build
  "tools.build script for psi uberjar.

   Usage:
     clojure -T:build uber        # build target/psi.jar + target/psi wrapper
     clojure -T:build clean       # remove target/"
  (:require
   [clojure.edn :as edn]
   [clojure.java.io :as io]
   [clojure.string :as str]
   [clojure.tools.build.api :as b]))

;; ---------------------------------------------------------------------------
;; Config
;; ---------------------------------------------------------------------------

(def class-dir "target/classes")
(def jar-file  "target/psi.jar")
(def wrapper   "target/psi")

(def basis
  (delay (b/create-basis {:project "deps.edn" :aliases [:run]})))

;; ---------------------------------------------------------------------------
;; Version
;; ---------------------------------------------------------------------------

(defn- version-string
  []
  (-> "bases/main/resources/psi/version.edn"
      slurp
      edn/read-string
      :version
      (or "unreleased")))

;; ---------------------------------------------------------------------------
;; Source paths — mirror :run alias exactly
;; ---------------------------------------------------------------------------

(def src-dirs
  ["bases/main/src"
   "bases/main/resources"
   "components/app-runtime/src"
   "components/agent-session/src"
   "components/agent-core/src"
   "components/ai/src"
   "components/engine/src"
   "components/query/src"
   "components/tui/src"
   "components/rpc/src"
   "extensions/auto-session-name/src"
   "extensions/commit-checks/src"
   "extensions/hello-ext/src"
   "extensions/lsp/src"
   "extensions/mcp-tasks-run/src"
   "extensions/mementum/src"
   "extensions/munera/src"
   "extensions/plan-state-learning/src"
   "extensions/work-on/src"
   "extensions/workflow-display/src"
   "extensions/workflow-loader/src"])

;; ---------------------------------------------------------------------------
;; Tasks
;; ---------------------------------------------------------------------------

(defn clean
  "Remove the target/ directory."
  [_]
  (b/delete {:path "target"}))

(defn uber
  "Build target/psi.jar and target/psi wrapper script.

   Requires Java 22+. The wrapper passes --enable-native-access=ALL-UNNAMED
   which is required by jline-terminal-ffm (TUI dependency)."
  [_]
  (let [version (version-string)]
    (println (str "Building psi " version " ..."))

    ;; 1. Clean
    (b/delete {:path "target"})

    ;; 2. Copy all source + resource trees into class-dir
    (println "  Copying sources ...")
    (b/copy-dir {:src-dirs   src-dirs
                 :target-dir class-dir})

    ;; 3. AOT compile psi.main (has :gen-class) and psi.app-runtime (has :gen-class)
    ;;    Everything else loads dynamically at runtime.
    (println "  AOT compiling entry points ...")
    (b/compile-clj {:basis      @basis
                    :src-dirs   src-dirs
                    :class-dir  class-dir
                    :ns-compile '[psi.main psi.app-runtime]
                    :compile-opts {:direct-linking true}})

    ;; 4. Assemble uberjar
    (println "  Assembling uberjar ...")
    (b/uber {:class-dir  class-dir
             :basis      @basis
             :uber-file  jar-file
             :main       'psi.main
             :manifest  {"Implementation-Title"   "psi"
                         "Implementation-Version" version}
             ;; Merge duplicate service files (common with Clojure libs)
             :conflict-handlers {"^META-INF/services/.*" :append
                                 "^META-INF/.*\\.SF$"    :ignore
                                 "^META-INF/.*\\.DSA$"   :ignore
                                 "^META-INF/.*\\.RSA$"   :ignore}})

    ;; 5. Write wrapper script
    (println "  Writing wrapper script ...")
    (let [wrapper-file (io/file wrapper)]
      (spit wrapper-file
            (str/join "\n"
                      ["#!/usr/bin/env bash"
                       "# psi launcher wrapper — requires Java 22+"
                       "# Generated by bb build:jar"
                       (str "# Version: " version)
                       "set -euo pipefail"
                       "SCRIPT_DIR=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\""
                       "exec java --enable-native-access=ALL-UNNAMED \\"
                       "     -jar \"${SCRIPT_DIR}/psi.jar\" \"$@\""
                       ""]))
      (.setExecutable wrapper-file true false))

    (println)
    (println (str "Built: " jar-file))
    (println (str "       " wrapper " (wrapper script)"))
    (println)
    (println "Run with:")
    (println (str "  java --enable-native-access=ALL-UNNAMED -jar " jar-file))
    (println (str "  " wrapper))))
