(ns psi.agent-session.session
  "Compatibility wrapper over `psi.session-state.model`.

   Canonical session model ownership now lives in `components/session-state/`.
   Keep this namespace temporarily so existing higher-level callers can migrate
   incrementally without changing all require sites at once."
  (:require
   [psi.session-state.model :as model]))

(def thinking-level-schema model/thinking-level-schema)
(def ui-type-schema model/ui-type-schema)
(def model-schema model/model-schema)
(def scoped-model-schema model/scoped-model-schema)
(def skill-schema model/skill-schema)
(def prompt-template-schema model/prompt-template-schema)
(def extension-schema model/extension-schema)
(def session-entry-kind-schema model/session-entry-kind-schema)
(def session-entry-schema model/session-entry-schema)
(def prompt-contribution-schema model/prompt-contribution-schema)
(def cache-breakpoint-schema model/cache-breakpoint-schema)
(def prompt-mode-schema model/prompt-mode-schema)
(def prompt-component-schema model/prompt-component-schema)
(def prompt-component-selection-schema model/prompt-component-selection-schema)
(def schedule-kind-schema model/schedule-kind-schema)
(def schedule-delivery-phase-schema model/schedule-delivery-phase-schema)
(def schedule-status-schema model/schedule-status-schema)
(def schedule-schema model/schedule-schema)
(def scheduler-state-schema model/scheduler-state-schema)
(def agent-session-schema model/agent-session-schema)
(def valid-session? model/valid-session?)
(def explain-session model/explain-session)
(def valid-skill? model/valid-skill?)
(def valid-extension? model/valid-extension?)
(def valid-session-entry? model/valid-session-entry?)
(def valid-schedule? model/valid-schedule?)
(def valid-scheduler-state? model/valid-scheduler-state?)
(def default-config model/default-config)
(def initial-session model/initial-session)
(def idle? model/idle?)
(def pending-message-count model/pending-message-count)
(def has-pending-messages? model/has-pending-messages?)
(def context-fraction-used model/context-fraction-used)
(def above-compaction-threshold? model/above-compaction-threshold?)
(def clamp-thinking-level model/clamp-thinking-level)
(def next-thinking-level model/next-thinking-level)
(def next-model model/next-model)
(def make-entry model/make-entry)
(def append-entry model/append-entry)
(def retry-error? model/retry-error?)
(def context-overflow-error? model/context-overflow-error?)
(def exponential-backoff-ms model/exponential-backoff-ms)
