;;; psi-dispatch-test.el --- Dispatch tests for psi Emacs frontend  -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(add-to-list 'load-path
             (file-name-directory (or load-file-name buffer-file-name)))
(add-to-list 'load-path
             (expand-file-name "../" (file-name-directory (or load-file-name buffer-file-name))))
(require 'psi-test-support)
(require 'psi)
(require 'psi-rpc)

(ert-deftest psi-compose-source-prefers-region-over-tail-draft ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (setf (psi-emacs-state-rpc-client psi-emacs--state)
          (psi-rpc-make-client :process-state 'running :transport-state 'ready))
    (setf (psi-emacs-state-transport-state psi-emacs--state) 'ready)
    (unwind-protect
        (progn
          (insert "prefix\nTAIL")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 8 nil))
          (set-mark 1)
          (goto-char 6)
          (activate-mark)
          (should (equal "prefi" (psi-emacs--composed-text))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-compose-source-uses-tail-draft-when-no-region ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (setf (psi-emacs-state-rpc-client psi-emacs--state)
          (psi-rpc-make-client :process-state 'running :transport-state 'ready))
    (unwind-protect
        (progn
          (insert "transcript\n")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state)
                (copy-marker (point-max) nil))
          (psi-emacs--ensure-input-area)
          (goto-char (psi-emacs--draft-end-position))
          (insert "Draft text")
          (deactivate-mark)
          (should (equal "Draft text" (psi-emacs--composed-text))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-ret-inserts-newline-and-does-not-send ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (progn
          (psi-emacs--ensure-input-area)
          (goto-char (psi-emacs--draft-end-position))
          (let ((calls (psi-test--capture-request-sends
                        (lambda ()
                          (insert "a")
                          (call-interactively (key-binding (kbd "RET"))))))
                (input-text nil))
            (setq input-text (psi-emacs--tail-draft-text))
            (should (equal "a\n" input-text))
            (should (equal '() calls))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-model-thinking-keybindings-are-installed ()
  (with-temp-buffer
    (psi-emacs-mode)
    (should (eq #'psi-emacs-set-model (key-binding (kbd "C-c m m"))))
    (should (eq #'psi-emacs-cycle-model-next (key-binding (kbd "C-c m n"))))
    (should (eq #'psi-emacs-cycle-model-prev (key-binding (kbd "C-c m p"))))
    (should (eq #'psi-emacs-set-thinking-level (key-binding (kbd "C-c m t"))))
    (should (eq #'psi-emacs-cycle-thinking-level (key-binding (kbd "C-c m c"))))))

(ert-deftest psi-interrupt-keybinding-is-installed ()
  (with-temp-buffer
    (psi-emacs-mode)
    (should (eq #'psi-emacs-interrupt (key-binding (kbd "C-c C-c"))))))

(ert-deftest psi-streaming-p-uses-explicit-run-state ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-assistant-in-progress psi-emacs--state) "legacy")
    (setf (psi-emacs-state-run-state psi-emacs--state) 'idle)
    (should-not (psi-emacs--streaming-p))
    (setf (psi-emacs-state-assistant-in-progress psi-emacs--state) nil)
    (setf (psi-emacs-state-run-state psi-emacs--state) 'streaming)
    (should (psi-emacs--streaming-p))))

(ert-deftest psi-send-routing-slash-first-and-streaming-steer-queue ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (progn
          (psi-emacs--ensure-input-area)
          (goto-char (psi-emacs--draft-end-position))
          (insert "hello")
          (let ((calls (psi-test--capture-request-sends
                        (lambda ()
                          (setf (psi-emacs-state-run-state psi-emacs--state) 'idle)
                          (psi-emacs-send-from-buffer nil)
                          ;; Input is consumed after first dispatch; subsequent
                          ;; non-slash sends are blank and should be blocked locally.
                          (psi-emacs-send-from-buffer nil)
                          (psi-emacs-send-from-buffer '(4))))))
            (should (eq 'streaming (psi-emacs-state-run-state psi-emacs--state)))
            (should (= 1 (length calls)))
            (should (equal "prompt" (caar calls)))
            (should (equal '((:message . "hello")) (cadar calls)))
            (should (equal "Cannot send empty input."
                           (psi-emacs-state-last-error psi-emacs--state)))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-queue-key-routes-queue-when-streaming-and-prompt-when-idle ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (progn
          (psi-emacs--ensure-input-area)
          (goto-char (psi-emacs--draft-end-position))
          (insert "queued")
          (let ((calls (psi-test--capture-request-sends
                        (lambda ()
                          (setf (psi-emacs-state-run-state psi-emacs--state) 'streaming)
                          (psi-emacs-queue-from-buffer)
                          ;; Input is consumed after first dispatch; second non-slash
                          ;; queue send is blank and blocked locally.
                          (setf (psi-emacs-state-run-state psi-emacs--state) 'idle)
                          (psi-emacs-queue-from-buffer)))))
            (should (= 1 (length calls)))
            (should (equal "prompt_while_streaming" (caar calls)))
            (should (equal '((:message . "queued") (:behavior . "queue")) (cadar calls)))
            (should (equal "Cannot send empty input."
                           (psi-emacs-state-last-error psi-emacs--state)))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-send-blocked-when-rpc-client-transport-not-ready ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-rpc-client psi-emacs--state)
          (psi-rpc-make-client :transport-state 'disconnected))
    (setf (psi-emacs-state-transport-state psi-emacs--state) 'disconnected)
    (insert "hello")
    (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
    (let ((calls nil))
      (cl-letf (((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional _callback)
                   (push (list op params) calls))))
        (psi-emacs-send-from-buffer nil))
      (should (equal '() calls))
      (should (eq 'error (psi-emacs-state-run-state psi-emacs--state)))
      (should (equal "Cannot run `prompt`: transport is disconnected. Reconnect with C-c C-r."
                     (psi-emacs-state-last-error psi-emacs--state)))
      (should (string-match-p "Error: Cannot run `prompt`" (buffer-string))))))

(ert-deftest psi-streaming-send-blocked-when-rpc-client-transport-not-ready ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-rpc-client psi-emacs--state)
          (psi-rpc-make-client :transport-state 'disconnected))
    (setf (psi-emacs-state-transport-state psi-emacs--state) 'disconnected)
    (setf (psi-emacs-state-run-state psi-emacs--state) 'streaming)
    (insert "queued")
    (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
    (let ((calls nil))
      (cl-letf (((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional _callback)
                   (push (list op params) calls))))
        (psi-emacs-queue-from-buffer))
      (should (equal '() calls))
      (should (eq 'error (psi-emacs-state-run-state psi-emacs--state)))
      (should (equal "Cannot run `prompt_while_streaming`: transport is disconnected. Reconnect with C-c C-r."
                     (psi-emacs-state-last-error psi-emacs--state)))
      (should (string-match-p "Error: Cannot run `prompt_while_streaming`" (buffer-string))))))

(ert-deftest psi-send-fails-when-dispatch-function-returns-nil ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--ensure-input-area)
    (goto-char (psi-emacs--draft-end-position))
    (insert "hello")
    (let ((calls nil))
      (cl-letf (((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional _callback)
                   (push (list op params) calls)
                   nil)))
        (psi-emacs-send-from-buffer nil))
      (should (equal '(("prompt" ((:message . "hello")))) calls))
      (should (eq 'error (psi-emacs-state-run-state psi-emacs--state)))
      (should (equal "Cannot run `prompt`: request dispatch failed. Reconnect with C-c C-r."
                     (psi-emacs-state-last-error psi-emacs--state)))
      (should (equal "hello" (psi-emacs--tail-draft-text)))
      (should-not (string-match-p "^User: hello$" (buffer-string))))))

(ert-deftest psi-send-empty-input-is-blocked-locally ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-run-state psi-emacs--state) 'streaming)
    (psi-emacs--ensure-input-area)
    (let ((calls nil))
      (cl-letf (((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional _callback)
                   (push (list op params) calls)
                   t)))
        (psi-emacs-send-from-buffer nil))
      (should (equal '() calls))
      ;; Blank input guard is local validation only; it does not mutate run-state.
      (should (eq 'streaming (psi-emacs-state-run-state psi-emacs--state)))
      (should (equal "Cannot send empty input."
                     (psi-emacs-state-last-error psi-emacs--state)))
      (should-not (string-match-p "^User:" (buffer-string))))))

(ert-deftest psi-set-model-dispatches-canonical-rpc-op ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (let ((calls (psi-test--capture-request-sends
                  (lambda ()
                    (psi-emacs-set-model "openai" "gpt-5.3-codex")))))
      (should (equal '(("set_model" ((:provider . "openai") (:model-id . "gpt-5.3-codex"))))
                     calls))
      (should (eq 'idle (psi-emacs-state-run-state psi-emacs--state))))))

(ert-deftest psi-set-model-no-arg-queries-runtime-catalog-and-dispatches-selection ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (let ((rpc-calls nil)
          (labels-seen nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt collection &rest _args)
                   (setq labels-seen (if (vectorp collection)
                                         (append collection nil)
                                       collection))
                   (car labels-seen)))
                ((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional callback)
                   (push (list op params) rpc-calls)
                   (when (and callback (equal op "query_eql"))
                     (funcall callback
                              '((:kind . :response)
                                (:ok . t)
                                (:op . "query_eql")
                                (:data . ((:result .
                                          ((:psi.agent-session/model-catalog .
                                            [((:provider . "openai")
                                              (:id . "gpt-5")
                                              (:name . "GPT-5")
                                              (:reasoning . t))
                                             ((:provider . "anthropic")
                                              (:id . "claude-sonnet-4-6")
                                              (:name . "Claude Sonnet 4.6")
                                              (:reasoning . t))])
                                           (:psi.agent-session/authenticated-providers . ["openai" "anthropic"]))))))))
                   t)))
        (psi-emacs-set-model))
      (setq rpc-calls (nreverse rpc-calls))
      (should (equal '("query_eql" "set_model") (mapcar #'car rpc-calls)))
      (should (equal `((:query . ,(psi-emacs--model-selector-query)))
                     (cadr (car rpc-calls))))
      (should (equal '((:provider . "anthropic") (:model-id . "claude-sonnet-4-6"))
                     (cadr (cadr rpc-calls))))
      (should (= 2 (length labels-seen)))
      (should (string-match-p "^(anthropic) claude-sonnet-4-6" (car labels-seen)))
      (should (string-match-p "^(openai) gpt-5" (cadr labels-seen))))))

(ert-deftest psi-set-model-selector-can-filter-to-authenticated-providers ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (let ((psi-emacs-model-selector-provider-scope 'authenticated)
          (rpc-calls nil)
          (labels-seen nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (_prompt collection &rest _args)
                   (setq labels-seen (if (vectorp collection)
                                         (append collection nil)
                                       collection))
                   (car labels-seen)))
                ((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional callback)
                   (push (list op params) rpc-calls)
                   (when (and callback (equal op "query_eql"))
                     (funcall callback
                              '((:kind . :response)
                                (:ok . t)
                                (:op . "query_eql")
                                (:data . ((:result .
                                          ((:psi.agent-session/model-catalog .
                                            [((:provider . "openai")
                                              (:id . "gpt-5")
                                              (:name . "GPT-5")
                                              (:reasoning . t))
                                             ((:provider . "anthropic")
                                              (:id . "claude-sonnet-4-6")
                                              (:name . "Claude Sonnet 4.6")
                                              (:reasoning . t))])
                                           (:psi.agent-session/authenticated-providers . ["anthropic"]))))))))
                   t)))
        (psi-emacs-set-model))
      (setq rpc-calls (nreverse rpc-calls))
      (should (equal '("query_eql" "set_model") (mapcar #'car rpc-calls)))
      (should (= 1 (length labels-seen)))
      (should (string-match-p "^(anthropic)" (car labels-seen)))
      (should (equal '((:provider . "anthropic") (:model-id . "claude-sonnet-4-6"))
                     (cadr (cadr rpc-calls)))))))

(ert-deftest psi-set-model-selector-empty-filtered-catalog-renders-feedback-and-skips-set-model ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (let ((psi-emacs-model-selector-provider-scope 'authenticated)
          (rpc-calls nil)
          (selector-called nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args)
                   (setq selector-called t)
                   ""))
                ((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional callback)
                   (push (list op params) rpc-calls)
                   (when (and callback (equal op "query_eql"))
                     (funcall callback
                              '((:kind . :response)
                                (:ok . t)
                                (:op . "query_eql")
                                (:data . ((:result .
                                          ((:psi.agent-session/model-catalog .
                                            [((:provider . "openai")
                                              (:id . "gpt-5")
                                              (:name . "GPT-5")
                                              (:reasoning . t))])
                                           (:psi.agent-session/authenticated-providers . []))))))))
                   t)))
        (psi-emacs-set-model))
      (setq rpc-calls (nreverse rpc-calls))
      (should (equal '("query_eql") (mapcar #'car rpc-calls)))
      (should-not selector-called)
      (should (string-match-p "No models available for providers with configured auth" (buffer-string))))))

(ert-deftest psi-cycle-model-dispatches-canonical-rpc-op ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (let ((calls (psi-test--capture-request-sends
                  (lambda ()
                    (psi-emacs-cycle-model-next)
                    (psi-emacs-cycle-model-prev)))))
      (should (equal '(("cycle_model" ((:direction . "next")))
                       ("cycle_model" ((:direction . "prev"))))
                     calls)))))

(ert-deftest psi-set-thinking-level-and-cycle-dispatch-canonical-rpc-ops ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (let ((calls (psi-test--capture-request-sends
                  (lambda ()
                    (psi-emacs-set-thinking-level "high")
                    (psi-emacs-cycle-thinking-level)))))
      (should (equal '(("set_thinking_level" ((:level . "high")))
                       ("cycle_thinking_level" nil))
                     calls)))))

(ert-deftest psi-model-thinking-controls-blocked-when-transport-not-ready ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-rpc-client psi-emacs--state)
          (psi-rpc-make-client :transport-state 'disconnected))
    (setf (psi-emacs-state-transport-state psi-emacs--state) 'disconnected)
    (let ((calls nil))
      (cl-letf (((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional _callback)
                   (push (list op params) calls))))
        (psi-emacs-set-model "openai" "gpt-5"))
      (should (equal '() calls))
      (should (eq 'error (psi-emacs-state-run-state psi-emacs--state)))
      (should (equal "Cannot run `set_model`: transport is disconnected. Reconnect with C-c C-r."
                     (psi-emacs-state-last-error psi-emacs--state)))
      (should (string-match-p "Error: Cannot run `set_model`" (buffer-string))))))

(ert-deftest psi-slash-send-and-queue-share-backend-command-dispatch-path ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((rpc-calls nil))
          (insert "  /handled  ")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
          (cl-letf (((symbol-value 'psi-emacs--slash-command-handler-function)
                     (lambda (&rest _args) t))
                    ((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls))))
            (psi-emacs-send-from-buffer nil)
            (setf (psi-emacs-state-run-state psi-emacs--state) 'idle)
            (let ((inhibit-read-only t))
              (erase-buffer))
            (insert "  /handled  ")
            (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
            (psi-emacs-queue-from-buffer))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '(("command" ((:text . "  /handled  ")))
                           ("command" ((:text . "  /handled  "))))
                         rpc-calls)))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-tree-dispatch-ignores-custom-command-handler-and-uses-backend-command ()
  "`/tree` routes through backend `command`, even when a custom slash handler declines it."
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((rpc-calls nil))
          (setf (psi-emacs-state-context-snapshot psi-emacs--state)
                '((:active-session-id . "s1")
                  (:sessions . (((:id . "s1") (:name . "main") (:is-active . t))
                                ((:id . "s2") (:name . "fork-1") (:is-active . nil))))))
          (cl-letf (((symbol-value 'psi-emacs--slash-command-handler-function)
                     (lambda (&rest _args) nil))
                    ((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls)
                       t)))
            (let ((result (psi-emacs--dispatch-compose-message "/tree s2")))
              (should (eq t (plist-get result :dispatched?)))
              (should-not (plist-get result :local-only?))))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '(("command" ((:text . "/tree s2")))) rpc-calls)))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-unknown-slash-dispatches-backend-command ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((slash-calls nil)
              (rpc-calls nil))
          (insert "/foo")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
          (cl-letf (((symbol-value 'psi-emacs--slash-command-handler-function)
                     (lambda (_state message)
                       (push message slash-calls)
                       nil))
                    ((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls))))
            (psi-emacs-send-from-buffer nil)
            (setf (psi-emacs-state-run-state psi-emacs--state) 'idle)
            (let ((inhibit-read-only t))
              (erase-buffer))
            (insert "/foo")
            (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
            (psi-emacs-queue-from-buffer))
          (setq slash-calls (nreverse slash-calls))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '() slash-calls))
          (should (equal '("command" "command") (mapcar #'car rpc-calls)))
          (should (equal '((:text . "/foo")) (cadr (car rpc-calls))))
          (should (equal '((:text . "/foo")) (cadr (cadr rpc-calls)))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-remember-slash-dispatches-backend-command ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((slash-calls nil)
              (rpc-calls nil))
          (insert "/remember blocked-path")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
          (cl-letf (((symbol-value 'psi-emacs--slash-command-handler-function)
                     (lambda (_state message)
                       (push message slash-calls)
                       nil))
                    ((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls))))
            (psi-emacs-send-from-buffer nil))
          (setq slash-calls (nreverse slash-calls))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '() slash-calls))
          (should (equal '("command") (mapcar #'car rpc-calls)))
          (should (equal '((:text . "/remember blocked-path"))
                         (cadr (car rpc-calls)))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-remember-slash-accepted-path-dispatches-backend-command ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((slash-calls nil)
              (rpc-calls nil))
          (insert "/remember accepted-path")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
          (cl-letf (((symbol-value 'psi-emacs--slash-command-handler-function)
                     (lambda (_state message)
                       (push message slash-calls)
                       nil))
                    ((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls))))
            (psi-emacs-send-from-buffer nil))
          (setq slash-calls (nreverse slash-calls))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '() slash-calls))
          (should (equal '("command") (mapcar #'car rpc-calls)))
          (should (equal '((:text . "/remember accepted-path"))
                         (cadr (car rpc-calls)))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-quit-slash-dispatches-command-and-exits-on-command-result ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((exit-called nil)
              (rpc-calls nil))
          (insert "/quit")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
          (cl-letf (((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls))))
            (psi-emacs-send-from-buffer nil))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '(("command" ((:text . "/quit")))) rpc-calls))
          (should-not exit-called)
          (cl-letf (((symbol-function 'psi-emacs--request-frontend-exit)
                     (lambda ()
                       (setq exit-called t))))
            (psi-emacs--handle-rpc-event
             '((:event . "command-result") (:data . ((:type . "quit"))))))
          (should exit-called))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-exit-slash-dispatches-command-and-exits-on-command-result ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((exit-called nil)
              (rpc-calls nil))
          (insert "/exit")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
          (cl-letf (((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls))))
            (psi-emacs-send-from-buffer nil))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '(("command" ((:text . "/exit")))) rpc-calls))
          (should-not exit-called)
          (cl-letf (((symbol-function 'psi-emacs--request-frontend-exit)
                     (lambda ()
                       (setq exit-called t))))
            (psi-emacs--handle-rpc-event
             '((:event . "command-result") (:data . ((:type . "quit"))))))
          (should exit-called))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-idle-resume-no-arg-dispatches-backend-command ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((rpc-calls nil)
              (no-arg-calls nil)
              (path-calls nil))
          (insert "/resume")
          (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker 1 nil))
          (cl-letf (((symbol-function 'psi-emacs--handle-idle-resume-no-arg)
                     (lambda (state)
                       (push state no-arg-calls)))
                    ((symbol-function 'psi-emacs--handle-idle-resume-explicit-path)
                     (lambda (_state session-path)
                       (push session-path path-calls)))
                    ((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls))))
            (psi-emacs-send-from-buffer nil))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '() no-arg-calls))
          (should (equal '() path-calls))
          (should (equal '(("command" ((:text . "/resume")))) rpc-calls)))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-frontend-action-select-resume-session-submits-selection-to-backend ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((rpc-calls nil)
              (labels-seen nil)
              (ui-action '((:ui/action-name . :select-resume-session)
                           (:ui/prompt . "Select a session to resume")
                           (:ui/items . [((:ui.item/id . "/tmp/sessions/a.ndedn")
                                          (:ui.item/label . "Alpha — /repo/alpha — /tmp/sessions/a.ndedn")
                                          (:ui.item/value . "/tmp/sessions/a.ndedn"))
                                         ((:ui.item/id . "/tmp/sessions/b.ndedn")
                                          (:ui.item/label . "Beta first — /repo/beta — /tmp/sessions/b.ndedn")
                                          (:ui.item/value . "/tmp/sessions/b.ndedn"))]))))
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_prompt collection &rest _args)
                       (setq labels-seen (if (vectorp collection)
                                             (append collection nil)
                                           collection))
                       (if (consp (car labels-seen))
                           (caar labels-seen)
                         (car labels-seen))))
                    ((symbol-function 'psi-emacs--dispatch-request)
                     (lambda (op params &optional _callback)
                       (push (list op params) rpc-calls)
                       t)))
            (psi-emacs--handle-rpc-event
             `((:event . "ui/frontend-action-requested")
               (:data . ((:request-id . "req-1")
                         (:prompt . "Select a session to resume")
                         (:ui/action . ,ui-action))))))
          (setq rpc-calls (nreverse rpc-calls))
          (let* ((call (car rpc-calls))
                 (params (cadr call)))
            (should (equal "frontend_action_result" (car call)))
            (should (equal "req-1" (alist-get :request-id params nil nil #'equal)))
            (should (equal "select-resume-session" (alist-get :action-name params nil nil #'equal)))
            (should (equal ui-action (alist-get :ui/action params nil nil #'equal)))
            (should (equal "submitted" (alist-get :status params nil nil #'equal)))
            (should (equal "/tmp/sessions/a.ndedn" (alist-get :value params nil nil #'equal))))
          (should (= 2 (length labels-seen)))
          (should (equal "Alpha — /repo/alpha — /tmp/sessions/a.ndedn"
                         (car (car labels-seen)))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-frontend-action-select-resume-session-cancel-sends-cancelled-result ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let ((rpc-calls nil)
              (ui-action '((:ui/action-name . :select-resume-session)
                           (:ui/prompt . "Select a session to resume")
                           (:ui/items . [((:ui.item/id . "/tmp/sessions/a.ndedn")
                                          (:ui.item/label . "Alpha — /repo/alpha — /tmp/sessions/a.ndedn")
                                          (:ui.item/value . "/tmp/sessions/a.ndedn"))]))))
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (&rest _args)
                       (signal 'quit nil)))
                    ((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls)
                       t)))
            (psi-emacs--handle-rpc-event
             `((:event . "ui/frontend-action-requested")
               (:data . ((:request-id . "req-2")
                         (:prompt . "Select a session to resume")
                         (:ui/action . ,ui-action))))))
          (setq rpc-calls (nreverse rpc-calls))
          (let* ((call (car rpc-calls))
                 (params (cadr call)))
            (should (equal "frontend_action_result" (car call)))
            (should (equal "req-2" (alist-get :request-id params nil nil #'equal)))
            (should (equal "select-resume-session" (alist-get :action-name params nil nil #'equal)))
            (should (equal ui-action (alist-get :ui/action params nil nil #'equal)))
            (should (equal "cancelled" (alist-get :status params nil nil #'equal)))
            (should (equal nil (alist-get :value params 'missing nil #'equal))))
          (should (string-empty-p (psi-emacs--tail-draft-text))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-frontend-action-select-session-submits-fork-point-payload ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state (psi-test--spawn-long-lived-process)))
    (unwind-protect
        (let* ((rpc-calls nil)
               (sort-hooks nil)
               (payload `((:selector/kind . :context-session)
                          (:selector/active-item-id . [:session "s1"])
                          (:selector/items . [((:item/id . [:session "s1"])
                                               (:item/kind . :session)
                                               (:item/session-id . "s1")
                                               (:item/display-name . "main")
                                               (:item/is-active . t)
                                               (:item/action . ((:action/kind . :switch-session)
                                                                (:action/session-id . "s1"))))
                                              ((:item/id . [:fork-point "e1"])
                                               (:item/kind . :fork-point)
                                               (:item/session-id . "s1")
                                               (:item/entry-id . "e1")
                                               (:item/parent-id . [:session "s1"])
                                               (:item/display-name . "Branch from here")
                                               (:item/action . ((:action/kind . :fork-session)
                                                                (:action/session-id . "s1")
                                                                (:action/entry-id . "e1"))))])))
               (ui-action '((:ui/action-name . :select-session)
                            (:ui/prompt . "Select a live session")
                            (:ui/order . :preserve)
                            (:ui/items . [((:ui.item/id . [:session "s1"])
                                           (:ui.item/label . "Main")
                                           (:ui.item/value . ((:action/kind . :switch-session)
                                                              (:action/session-id . "s1"))))
                                          ((:ui.item/id . [:fork-point "e1"])
                                           (:ui.item/label . "⎇ Branch from here")
                                           (:ui.item/value . ((:action/kind . :fork-session)
                                                              (:action/session-id . "s1")
                                                              (:action/entry-id . "e1"))))])))
               (frame `((:event . "ui/frontend-action-requested")
                        (:data . ((:request-id . "req-3")
                                  (:prompt . "Select a live session")
                                  (:ui/action . ,ui-action))))))
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (&rest _args)
                       (setq sort-hooks (list (plist-get completion-extra-properties :display-sort-function)
                                              (plist-get completion-extra-properties :cycle-sort-function)))
                       "⎇ Branch from here"))
                    ((symbol-value 'psi-emacs--send-request-function)
                     (lambda (_state op params &optional _callback)
                       (push (list op params) rpc-calls)
                       t)))
            (psi-emacs--handle-rpc-event frame))
          (setq rpc-calls (nreverse rpc-calls))
          (should (equal '(identity identity) sort-hooks))
          (let* ((call (car rpc-calls))
                 (params (cadr call))
                 (value (alist-get :value params nil nil #'equal)))
            (should (equal "frontend_action_result" (car call)))
            (should (equal "req-3" (alist-get :request-id params nil nil #'equal)))
            (should (equal "select-session" (alist-get :action-name params nil nil #'equal)))
            (should (equal ui-action (alist-get :ui/action params nil nil #'equal)))
            (should (equal "submitted" (alist-get :status params nil nil #'equal)))
            (should (equal :fork-session (alist-get :action/kind value nil nil #'equal)))
            (should (equal "s1" (alist-get :action/session-id value nil nil #'equal)))
            (should (equal "e1" (alist-get :action/entry-id value nil nil #'equal)))))
      (when (process-live-p (psi-emacs-state-process psi-emacs--state))
        (delete-process (psi-emacs-state-process psi-emacs--state))))))

(ert-deftest psi-on-rpc-event-defers-frontend-action-prompts-out-of-process-filter-path ()
  "Frontend action prompts should be deferred off the process filter path.

Regression: bare `/tree` now arrives as `ui/frontend-action-requested`. Prompting
synchronously from the RPC event callback can make Emacs appear to do nothing."
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (let* ((scheduled-fn nil)
           (handled nil)
           (frame '((:event . "ui/frontend-action-requested")
                    (:data . ((:request-id . "req-tree")
                              (:ui/action . ((:ui/action-name . :select-session)
                                             (:ui/prompt . "Select a live session")
                                             (:ui/items . []))))))))
      (cl-letf (((symbol-function 'run-with-idle-timer)
                 (lambda (_secs _repeat fn &rest _args)
                   (setq scheduled-fn fn)
                   'fake-timer))
                ((symbol-function 'psi-emacs--handle-rpc-event)
                 (lambda (frm)
                   (setq handled frm)))
                ((symbol-function 'get-buffer-window)
                 (lambda (&rest _args) nil))
                ((symbol-function 'frame-live-p)
                 (lambda (&rest _args) nil)))
        (psi-emacs--on-rpc-event (current-buffer) frame)
        (should (null handled))
        (should (functionp scheduled-fn))
        (funcall scheduled-fn)
        (should (equal frame handled))))))


;;; Command/session dispatch tests moved to psi-dispatch-command-test.el

(provide 'psi-dispatch-test)

;;; psi-dispatch-test.el ends here
