;;; psi-streaming-history-test.el --- Input/history replay tests for psi Emacs frontend  -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'subr-x)

(add-to-list 'load-path
             (expand-file-name "../" (file-name-directory (or load-file-name buffer-file-name))))
(require 'psi)
(require 'psi-rpc)
(require 'psi-test-support)

(ert-deftest psi-smoke-start-handshake-send-stream-abort-reconnect ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker (point-min) nil))
    (let ((sent nil)
          (stop-count 0)
          (restart-count 0))
      (cl-letf (((symbol-value 'psi-emacs--send-request-function)
                 (lambda (_state op params &optional _callback)
                   (push (list op params) sent)))
                ((symbol-function 'psi-rpc-stop!)
                 (lambda (_client)
                   (setq stop-count (1+ stop-count))))
                ((symbol-function 'psi-emacs--start-rpc-client)
                 (lambda (_buffer)
                   (setq restart-count (1+ restart-count)))))
        (let ((client (psi-rpc-make-client :process-state 'running :transport-state 'handshaking)))
          (psi-emacs--on-rpc-state-change (current-buffer) client)
          (setf (psi-rpc-client-transport-state client) 'ready)
          (psi-emacs--on-rpc-state-change (current-buffer) client)
          (should (string= "psi [ready/running/idle] tools:collapsed" header-line-format)))
        (insert "hello from smoke")
        (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker (point-min) nil))
        (psi-emacs-send-from-buffer nil)
        (psi-emacs--handle-rpc-event
         '((:event . "assistant/delta") (:data . ((:text . "Hi")))))
        (psi-emacs--handle-rpc-event
         '((:event . "tool/start") (:data . ((:tool-id . "t-smoke") (:text . "start")))))
        (psi-emacs--handle-rpc-event
         '((:event . "tool/result") (:data . ((:tool-id . "t-smoke") (:text . "done")))))
        (should (string-match-p "ψ: Hi" (buffer-string)))
        (should (string-match-p "t-smoke success" (buffer-string)))
        (psi-emacs-abort)
        (should-not (psi-emacs-state-assistant-in-progress psi-emacs--state))
        (setf (psi-emacs-state-rpc-client psi-emacs--state) (psi-rpc-make-client))
        (set-buffer-modified-p nil)
        (psi-emacs-reconnect)
        (setq sent (nreverse sent))
        (should (equal '("get_messages" "query_eql" "prompt" "abort")
                       (mapcar #'car sent)))
        (should (equal '((:message . "hello from smoke"))
                       (cadr (nth 2 sent))))
        (should (= 1 stop-count))
        (should (= 1 restart-count))
        (should (psi-emacs--input-separator-marker-valid-p))
        (should (string-prefix-p "ψ\n─" (buffer-string)))))))

(ert-deftest psi-input-area-creates-separator-and-start-marker ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (insert "existing transcript")
    (setf (psi-emacs-state-draft-anchor psi-emacs--state)
          (copy-marker (point-max) nil))
    (cl-letf (((symbol-function 'psi-emacs--projection-window-width)
               (lambda () 20)))
      (psi-emacs--ensure-input-area)
      (let ((sep (psi-emacs--input-separator-marker-cache)))
        (should (markerp sep))
        (should (eq ?─ (char-after (marker-position sep))))
        (should (= 20 (psi-emacs--input-separator-current-width)))
        (should (= (psi-emacs--input-start-position)
                   (marker-position (psi-emacs-state-draft-anchor psi-emacs--state))))))))

(ert-deftest psi-input-separator-refreshes-width-when-window-width-changes ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state)
          (copy-marker (point-max) nil))
    (cl-letf (((symbol-function 'psi-emacs--projection-window-width)
               (lambda () 20)))
      (psi-emacs--ensure-input-area)
      (should (= 20 (psi-emacs--input-separator-current-width))))
    (cl-letf (((symbol-function 'psi-emacs--projection-window-width)
               (lambda () 33)))
      (should (psi-emacs--input-separator-needs-refresh-p))
      (psi-emacs--ensure-input-area)
      (should-not (psi-emacs--input-separator-needs-refresh-p))
      (should (= 33 (psi-emacs--input-separator-current-width))))))

(ert-deftest psi-send-copies-input-to-transcript-and-clears-input ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--ensure-input-area)
    (goto-char (psi-emacs--draft-end-position))
    (insert "hello input")
    (let ((calls (psi-test--capture-request-sends
                  (lambda ()
                    (psi-emacs-send-from-buffer nil)))))
      (should (equal '(("prompt" ((:message . "hello input")))) calls))
      (should (string-empty-p (psi-emacs--tail-draft-text)))
      (should (string-match-p "^User: hello input" (buffer-string))))))

(ert-deftest psi-send-omits-input-separator-from-first-prompt-when-anchor-drifts ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--ensure-input-area)
    (setf (psi-emacs-state-draft-anchor psi-emacs--state)
          (copy-marker (marker-position (psi-emacs--input-separator-marker-cache)) nil))
    (goto-char (psi-emacs--draft-end-position))
    (insert "hello input")
    (should (equal "hello input" (psi-emacs--tail-draft-text)))
    (let ((calls (psi-test--capture-request-sends
                  (lambda ()
                    (psi-emacs-send-from-buffer nil)))))
      (should (equal '(("prompt" ((:message . "hello input")))) calls)))))

(ert-deftest psi-send-does-not-copy-input-when-dispatch-not-confirmed ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-transport-state psi-emacs--state) 'ready)
    (psi-emacs--ensure-input-area)
    (goto-char (psi-emacs--draft-end-position))
    (insert "hello input")
    (cl-letf (((symbol-value 'psi-emacs--send-request-function)
               (lambda (_state _op _params &optional _callback)
                 nil)))
      (psi-emacs-send-from-buffer nil))
    (should (equal "hello input" (psi-emacs--tail-draft-text)))
    (should-not (string-match-p "^User: hello input" (buffer-string)))))

(ert-deftest psi-send-repairs-missing-input-separator-after-submit ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--ensure-input-area)
    (goto-char (psi-emacs--draft-end-position))
    (insert "hello input")
    (let ((sep (psi-emacs--input-separator-marker-cache)))
      (save-excursion
        (goto-char (marker-position sep))
        (let ((inhibit-read-only t))
          (delete-char 1)
          (insert "x"))))
    (should-not (psi-emacs--input-separator-marker-valid-p))
    (let ((calls (psi-test--capture-request-sends
                  (lambda ()
                    (psi-emacs-send-from-buffer nil)))))
      (should (equal '(("prompt" ((:message . "hello input")))) calls))
      (should (psi-emacs--input-separator-marker-valid-p))
      (should (string-empty-p (psi-emacs--tail-draft-text)))
      (should (string-match-p "^User: hello input" (buffer-string))))))

(ert-deftest psi-replay-session-messages-with-input-area-stays-above-separator ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state)
          (copy-marker (point-max) nil))
    (psi-emacs--ensure-input-area)
    (psi-emacs--replay-session-messages
     '(((:role . :assistant) (:text . "boot ok"))))
    (let ((sep-pos (psi-emacs--input-separator-position)))
      (should (integerp sep-pos))
      (should (string-match-p "^ψ: boot ok$" (buffer-string)))
      (should (< (or (string-match-p "ψ: boot ok" (buffer-string)) 0)
                 sep-pos)))))

(ert-deftest psi-replay-session-messages-string-role-user-renders-as-user ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state)
          (copy-marker (point-max) nil))
    (psi-emacs--ensure-input-area)
    (psi-emacs--replay-session-messages
     '(((:role . "user")      (:content . "hello"))
       ((:role . "assistant") (:content . "hi there"))))
    (let ((text (buffer-string)))
      (should (string-match-p "User: hello" text))
      (should (string-match-p "ψ: hi there" text))
      (should-not (string-match-p "ψ: hello" text))
      (should-not (string-match-p "User: hi there" text)))))

(ert-deftest psi-replay-session-messages-keyword-role-user-renders-as-user ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state)
          (copy-marker (point-max) nil))
    (psi-emacs--ensure-input-area)
    (psi-emacs--replay-session-messages
     '(((:role . :user)      (:content . "hello"))
       ((:role . :assistant) (:content . "hi there"))))
    (let ((text (buffer-string)))
      (should (string-match-p "User: hello" text))
      (should (string-match-p "ψ: hi there" text)))))

(ert-deftest psi-replay-session-messages-structured-assistant-content-renders-text ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state)
          (copy-marker (point-max) nil))
    (psi-emacs--ensure-input-area)
    (psi-emacs--replay-session-messages
     '(((:role . "assistant")
        (:content . ((:kind . :structured)
                     (:blocks . [((:kind . :text)
                                  (:text . "boot ok"))]))))))
    (should (string-match-p "ψ: boot ok" (buffer-string)))))

(ert-deftest psi-replay-session-messages-assistant-error-message-renders-text ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state)
          (copy-marker (point-max) nil))
    (psi-emacs--ensure-input-area)
    (psi-emacs--replay-session-messages
     '(((:role . "assistant")
        (:content . [])
        (:error-message . "Validation failed"))))
    (should (string-match-p (regexp-quote "ψ: [error] Validation failed")
                            (buffer-string)))))

(ert-deftest psi-input-history-m-p-m-n-navigates-submissions ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--history-record-input "first")
    (psi-emacs--history-record-input "second")
    (psi-emacs--ensure-input-area)
    (goto-char (psi-emacs--draft-end-position))
    (insert "draft")
    (psi-emacs-previous-input)
    (should (equal "second" (psi-emacs--tail-draft-text)))
    (psi-emacs-previous-input)
    (should (equal "first" (psi-emacs--tail-draft-text)))
    (psi-emacs-next-input)
    (should (equal "second" (psi-emacs--tail-draft-text)))
    (psi-emacs-next-input)
    (should (equal "draft" (psi-emacs--tail-draft-text)))))

(ert-deftest psi-input-history-navigation-works-with-projection-present ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker (point-max) nil))
    (psi-emacs--history-record-input "first")
    (psi-emacs--history-record-input "second")
    (psi-emacs--ensure-input-area)
    (psi-emacs--handle-rpc-event
     '((:event . "footer/updated")
       (:data . ((:path-line . "~/psi-main")
                 (:usage-parts . ["latency" "12ms"])))))
    (psi-emacs--replace-input-text "draft")
    (goto-char (point-max))
    (psi-emacs-previous-input)
    (should (equal "second" (psi-emacs--tail-draft-text)))
    (psi-emacs-previous-input)
    (should (equal "first" (psi-emacs--tail-draft-text)))
    (psi-emacs-next-input)
    (should (equal "second" (psi-emacs--tail-draft-text)))
    (psi-emacs-next-input)
    (should (equal "draft" (psi-emacs--tail-draft-text)))))

(ert-deftest psi-input-history-navigation-survives-guarded-before-change-hooks ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker (point-max) nil))
    (psi-emacs--history-record-input "first")
    (psi-emacs--history-record-input "second")
    (psi-emacs--ensure-input-area)
    (psi-emacs--replace-input-text "draft")
    (add-hook 'before-change-functions
              (lambda (_beg _end)
                (unless psi-emacs--allow-protected-input-edit
                  (signal 'text-read-only nil)))
              nil
              t)
    (psi-emacs-previous-input)
    (should (equal "second" (psi-emacs--tail-draft-text)))))

(ert-deftest psi-input-area-scrubs-inherited-read-only-properties ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker (point-max) nil))
    (psi-emacs--ensure-input-area)
    (let* ((range (psi-emacs--input-range))
           (start (car range)))
      (let ((inhibit-read-only t))
        (insert (propertize "draft" 'read-only t)))
      (should (get-text-property start 'read-only))
      (psi-emacs--clear-read-only-props-in-input-range)
      (should-not (get-text-property start 'read-only)))))

(ert-deftest psi-projection-boundary-does-not-make-input-read-only ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (setf (psi-emacs-state-draft-anchor psi-emacs--state) (copy-marker (point-max) nil))
    (psi-emacs--ensure-input-area)
    (psi-emacs--handle-rpc-event
     '((:event . "footer/updated")
       (:data . ((:path-line . "~/psi-main")
                 (:usage-parts . ["latency" "12ms"])))))
    (let* ((range (psi-emacs--input-range))
           (start (car range)))
      (should-not (get-text-property start 'read-only))
      (should-not (get-text-property start 'front-sticky))
      (let ((inhibit-read-only t))
        (goto-char start)
        (insert "draft"))
      (should (equal "draft" (psi-emacs--tail-draft-text))))))

(ert-deftest psi-search-input-history-signals-error-when-not-psi-buffer ()
  (with-temp-buffer
    (should-error (psi-emacs-search-input-history) :type 'user-error)))

(ert-deftest psi-search-input-history-signals-error-when-history-empty ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (should-error (psi-emacs-search-input-history) :type 'user-error)))

(ert-deftest psi-search-input-history-cancel-leaves-input-and-nav-state-unchanged ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--history-record-input "first")
    (psi-emacs--history-record-input "second")
    (psi-emacs--ensure-input-area)
    (psi-emacs--replace-input-text "draft")
    ;; Simulate C-g / empty-string cancel: completing-read returns "".
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt _collection &rest _args) "")))
      (psi-emacs-search-input-history))
    (should (equal "draft" (psi-emacs--tail-draft-text)))
    (should (null (psi-emacs-state-input-history-stash psi-emacs--state)))
    (should (null (psi-emacs-state-input-history-index psi-emacs--state)))))

(ert-deftest psi-search-input-history-selection-replaces-input-and-stashes-draft ()
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--history-record-input "first")
    (psi-emacs--history-record-input "second")
    (psi-emacs--ensure-input-area)
    (psi-emacs--replace-input-text "my draft")
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt _collection &rest _args) "first")))
      (psi-emacs-search-input-history))
    (should (equal "first" (psi-emacs--tail-draft-text)))
    (should (equal "my draft" (psi-emacs-state-input-history-stash psi-emacs--state)))
    ;; Navigation index reset to nil so M-p starts from top of history.
    (should (null (psi-emacs-state-input-history-index psi-emacs--state)))))

(ert-deftest psi-search-input-history-m-n-immediately-after-selection-errors ()
  "M-n with nil index (no navigation started) signals user-error."
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--history-record-input "first")
    (psi-emacs--history-record-input "second")
    (psi-emacs--ensure-input-area)
    (psi-emacs--replace-input-text "my draft")
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt _collection &rest _args) "first")))
      (psi-emacs-search-input-history))
    ;; index is nil after selection; M-n has no history position to step back from.
    (should-error (psi-emacs-next-input) :type 'user-error)))

(ert-deftest psi-search-input-history-m-p-then-m-n-recovers-selected-entry ()
  "After search-selection, M-p steps into history; M-n returns to selected entry."
  (with-temp-buffer
    (psi-emacs-mode)
    (setq-local psi-emacs--state (psi-emacs--initialize-state nil))
    (psi-emacs--history-record-input "first")
    (psi-emacs--history-record-input "second")
    (psi-emacs--ensure-input-area)
    (psi-emacs--replace-input-text "my draft")
    (cl-letf (((symbol-function 'completing-read)
               (lambda (_prompt _collection &rest _args) "first")))
      (psi-emacs-search-input-history))
    ;; Input is now "first"; stash is "my draft"; index is nil.
    (should (equal "first" (psi-emacs--tail-draft-text)))
    ;; M-p: stashes "first", steps to index 0 = "second".
    (psi-emacs-previous-input)
    (should (equal "second" (psi-emacs--tail-draft-text)))
    ;; M-n: recovers M-p stash = "first", resets navigation.
    (psi-emacs-next-input)
    (should (equal "first" (psi-emacs--tail-draft-text)))))

(provide 'psi-streaming-history-test)
;;; psi-streaming-history-test.el ends here
